let dados = { 
    zumbi: { titulo: "Zumbi",
         descricao: "Os zumbis no Minecraft são criaturas hostis que surgem durante a noite e em áreas escuras. Caracterizados por seus movimentos lentos e gemidos característicos, eles representam um dos primeiros desafios que os jogadores enfrentam ao explorar o mundo do jogo.",
         link: "https://minecraft.fandom.com/pt/wiki/Zumbi",
          tags: "zumbi" },
    esqueleto: { titulo: "Esqueleto",
         descricao: "Os esqueletos são criaturas hostis que surgem em diversos biomas do Minecraft, especialmente em áreas escuras como cavernas e florestas. Eles são facilmente reconhecidos por sua aparência esquelética, com um arco nas mãos.", 
         link: "https://minecraft.fandom.com/pt-br/wiki/Esqueleto",
         tags: "esqueleto" }, 
    creeper: { titulo: "Creeper",
         descricao: "Os Creepers são, sem dúvida, uma das criaturas mais icônicas e temidas do Minecraft. Com sua aparência peculiar e explosões devastadoras, eles se tornaram um símbolo do jogo. Os Creepers são mobs hostis que se assemelham a plantas ambulantes. Eles possuem um corpo alongado, verde e com uma boca enorme que se abre antes de explodir.",
         link: "https://minecraft.fandom.com/pt/wiki/Creeper", 
         tags: "creeper" }, 
    aranha: { titulo: "Aranha", 
        descricao: "As aranhas são criaturas hostis que se escondem em lugares escuros, como cavernas e florestas. Elas são mais rápidas que os zumbis e podem pular para atacar seus alvos.", 
        link: "https://minecraft.fandom.com/pt/wiki/Aranha", 
        tags: "aranha" }, 
    enderman: { titulo: "Enderman", 
        descricao: "Os Endermen são criaturas hostis que se teleportam e habitam o The End. Eles são altos e magros, com olhos roxos brilhantes.", 
        link: "https://minecraft.fandom.com/pt/wiki/Enderman", 
        tags: "enderman" },
}
